### ISSUE TITLE
400 Error when publishing

### ISSUE THREAD

**Issue by DewarM** [semantic-release/gitlab#11] opened 2018-02-06 17:48 UTC
As title suggests I'm getting a 400 error when publishing to gitlab. I think this is due to 
`    body: {tag_name: gitTag, ref: gitHead, release_description: notes}, // eslint-disable-line camelcase
` in `publish.js`

I think this is submitting the incorrect payload. As outlined in the gitlab docs:
- id (required) - The ID or URL-encoded path of the project owned by the authenticated user
- tag_name (required) - The name of a tag
- description (required) - Release notes with markdown support`

Is this the case or am I totally off? Happy to do a PR for this if I am correct - just wanted to know if I was correct in my guess.
Thanks for the plugin! :D

**Comment by pvdlg** [comment] 2018-02-06 18:43
It seems it's a duplicate of semantic-release/semantic-release#641 (which is open in the wrong repo).

We are doing a `PUT` but we should do a `POST` here:
https://github.com/semantic-release/gitlab/blob/9cf0a55d2adbb768f795dc1e1798fcbdb2eb8dc3/lib/publish.js#L17

If you can do a PR that'd be great!

You would would also have to changes the tests:
https://github.com/semantic-release/gitlab/blob/9cf0a55d2adbb768f795dc1e1798fcbdb2eb8dc3/test/publish.test.js#L42
https://github.com/semantic-release/gitlab/blob/9cf0a55d2adbb768f795dc1e1798fcbdb2eb8dc3/test/integration.test.js#L60
https://github.com/semantic-release/gitlab/blob/9cf0a55d2adbb768f795dc1e1798fcbdb2eb8dc3/test/integration.test.js#L84

**Comment by pvdlg** [comment] 2018-02-06 18:55
Also, your right the payload is wrong, `release_description` should be replaced by `description`.
Not sure why the GitLab API to create a tag with a description is so different than the one to add a release note. I guess I got confused between the two when I wrote the code :)

**Comment by pvdlg** [comment] 2018-02-07 18:41
@DewarM would you like to try a PR for this issue? Let me know if you need help.

**Comment by DewarM** [comment] 2018-02-08 09:35
@pvdlg I think the PR should be done - let me know if I need to make some changes!

**Closed** 2018-02-09 09:30 UTC
Labels: bug, help wanted, plugin:gitlab

**Comment by kal727** [comment] 2018-03-06 20:07
@pvdlg I got around to playing with this plugin and I think there might still be an issue related to this 400 Bad Request.  Currently, GitLab requires an existing Tag to create a Release, and I don't think you can create a Tag from a Release (https://docs.gitlab.com/ce/api/tags.html). I think publish.js needs to first post to create a Tag, then post a Release to that newly created Tag.

**Comment by pvdlg** [comment] 2018-03-06 20:15
No because in recent version of semantic-release the core creates the tag for you. So when the plugin is called the tag is already created for you. So the plugin just have to create the release.
