### ISSUE TITLE
HTTPError: Response code 500 (Internal Server Error)

### ISSUE THREAD

**Issue by joelnet** [semantic-release/gitlab#157] opened 2020-07-31 01:03 UTC
I'm getting an error `HTTPError: Response code 500 (Internal Server Error)` and I'm not sure where to start looking. Can someone point me in the right direction?

Gitlab version:  12.7.5-ee
semantic-release: 17.1.1
@semantic-release/gitlab: 6.0.4

environment variables set:
- `GITLAB_TOKEN`
- `GITLAB_URL`

package.json:

```javascript
  "release": {
    "branch": "master",
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/npm",
      [
        "@semantic-release/exec",
        {
          "publishCmd": "./scripts/publish.sh ${nextRelease.version}"
        }
      ],
      [
        "@semantic-release/gitlab",
        {
          "assets": [
            {
              "path": "dist/*",
              "label": "distribution"
            }
          ]
        }
      ]
    ]
  }
```

related logs:
```
[12:18:39 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
 [12:18:39 AM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://gitlabdev.paciolan.info/api/v4)
 [12:18:39 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/gitlab"
 [12:18:39 AM] [semantic-release] › ℹ  Found git tag v3.90.12 associated with version 3.90.12 on branch master
 [12:18:39 AM] [semantic-release] › ℹ  Found 2 commits since last release
[12:18:59 AM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/gitlab"
 [12:18:59 AM] [semantic-release] [@semantic-release/gitlab] › ℹ  Uploaded file: /uploads/3077c3c86a4d7327bf264b6e577af63a/webpack-bundle-analyzer-report.html
 [12:18:59 AM] [semantic-release] [@semantic-release/gitlab] › ℹ  Uploaded file: /uploads/57b429d4ef251ab2b249f82e8f28185e/manifest.json
 [12:18:59 AM] [semantic-release] [@semantic-release/gitlab] › ℹ  Uploaded file: /uploads/1de264bada56285c66fe3c3e1d2e86a7/demo.html
 [12:18:59 AM] [semantic-release] [@semantic-release/gitlab] › ℹ  Uploaded file: /uploads/88ab781114803435712edc4a8589b6f8/demo.js
 [12:18:59 AM] [semantic-release] [@semantic-release/gitlab] › ℹ  Uploaded file: /uploads/f2a6723132ac5e488947cc8247d3376c/component.js
 [12:19:00 AM] [semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/gitlab"
 [12:19:00 AM] [semantic-release] › ✖  An error occurred while running semantic-release: { HTTPError: Response code 500 (Internal Server Error)
     at EventEmitter.emitter.on (/builds/development/application/ticketing/javascript/my-account-2-component/node_modules/got/dist/source/as-promise.js:118:31)
     at process._tickCallback (internal/process/next_tick.js:68:7) name: 'HTTPError', pluginName: '@semantic-release/gitlab' }
 { HTTPError: Response code 500 (Internal Server Error)
     at EventEmitter.emitter.on (/builds/development/application/ticketing/javascript/my-account-2-component/node_modules/got/dist/source/as-promise.js:118:31)
     at process._tickCallback (internal/process/next_tick.js:68:7) name: 'HTTPError', pluginName: '@semantic-release/gitlab' }
 ERROR: Job failed: exit code 1
```

Thanks!

**Comment by joelnet** [comment] 2020-08-11 20:08
After upgrading Gitlab to `13.2.3-ee` I am now seeing a 400. It looks like the same error in issue #158

**Comment by nfriend** [comment] 2020-12-03 13:49
@joelnet https://github.com/semantic-release/gitlab/issues/158 has been fixed by https://github.com/semantic-release/gitlab/pull/179, so if this is indeed the same root cause, this issue should now be fixed 👍 

I'll close for now, but please reopen if you continue to see this behavior!

**Comment by nfriend** [comment] 2020-12-03 13:52
> I'll close for now

@joelnet Forgot I don't have access to close issues in this repo 🤦 Would you mind closing if you agree? 🙏

**Comment by fgreinacher** [comment] 2022-07-15 17:26
Closing as per the comments above. Feel free to reopen!

**Closed by fgreinacher** 2022-07-15 17:26 UTC
