### ISSUE TITLE
Authentication fails

### ISSUE THREAD

**Issue by stenaloom** [semantic-release/gitlab#151] opened 2020-06-03 18:39 UTC
Trying to implement semantic-release for Gitlab. I have a non-traditional setup with the original repository in Github that is mirrored to Gitlab. CI job runs on Gitlab. 
The Gitlab token is defined in variables and I tested from command line that it works.
I think the issue is in the url "https://[secure]@gitlab.com". There should be a username. 

Possibly the script tries to connect to Gitlab but uses Github syntax for URL?
Ideally I would like to publish to both.

[2:33:43 PM] [semantic-release] » ×  An error occurred while running semantic-release: Error: Command failed with exit code 128: git ls-remote --heads https://[secure]@gitlab.com/******/Release_test.git
 Logon failed, use ctrl+c to cancel basic credential prompt.
 remote: HTTP Basic: Access denied
 fatal: Authentication failed for 'https://gitlab.com/*****/Release_test.git/'

**Comment by damusix** [comment] 2020-08-08 05:21
Been going at this for hours I'm getting the same thing

**Comment by stenaloom** [comment] 2020-08-08 05:27
> Been going at this for hours I'm getting the same thing

Try adding the username and token to your repository url in package.json

**Comment by damusix** [comment] 2020-08-08 05:46
nothing :/

**Comment by ciddsultan** [comment] 2020-09-06 18:03
I am having the same problem on Windows, shell runner

**Comment by ciddsultan** [comment] 2020-09-06 21:58
> nothing :/

you might want to check if the enviroment variable: `GITLAB_TOKEN` is set correctly

**Comment by nfriend** [comment] 2020-12-03 21:21
@ciddsultan @damusix Were you able to find a root cause of this issue?

Unfortunately I don't have any specific recommendations for you, but in case it helps, [here's a working example](https://gitlab.com/gitlab-examples/semantic-release-npm) (and [an accompanying tutorial](https://gitlab.com/gitlab-examples/semantic-release-npm)) of a GitLab project that uses a [project access token](https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html) for authentication.

**Comment by dsandor** [comment] 2021-04-21 13:07
Hi, I know this issue is older but I wanted to drop by and let you know what solved my issue.

Reference: https://docs.gitlab.com/ee/integration/kerberos.html#http-basic-access-denied-when-cloning

Before I call `semantic-release` I set the git option `http.emptyPath` to true. This allows semantic-release to properly use the https url for the repository path.

So this line, before calling semantic-release did the trick for me:

`git config --global http.emptyAuth true`

Example gitlab ci yaml file snippet:

```
  after_script:
    - git config --global http.emptyAuth true
    # Semantic Release - Label code (only once)
    - npx -p @semantic-release/changelog -p semantic-release -p @semantic-release/gitlab -p @semantic-release/commit-analyzer -p @semantic-release/release-notes-generator semantic-release
```

**Comment by centerorbit** [comment] 2021-08-03 18:12
For others as well, I had forgotten to add the CI variable `GITLAB_TOKEN`, as mentioned here:

https://docs.gitlab.com/ee/ci/examples/semantic-release.html#set-up-cicd-variables

**Comment by basaa** [comment] 2021-09-29 10:49
I had the same issue, and I realized that I restricted the access to my repositories (only SSH); I changed it to both (SSH and HTTPS) and it worked.

**Comment by MikeYermolayev** [comment] 2021-11-30 15:16
Oh my god..... My branch was not marked as protected but GITLAB_TOKEN env was marked as *protected*...

**Closed** 2022-07-15 17:24 UTC

**Comment by liz72703** [comment] 2024-12-02 17:27
> Oh my god..... My branch was not marked as protected but GITLAB_TOKEN env was marked as **protected**... -_-
> 
> Everything works OK after fixing it

OMG is right!  THANK YOU Misha, this saved me.
