### ISSUE TITLE
Cannot upload assets

### ISSUE THREAD

**Issue by renedacosta** [semantic-release/gitlab#147] opened 2020-04-10 21:36 UTC
Hi all,

I'm having an issue with uploading assets along with my release.
It seems to find the files fine but is unable to finalize the publish step, giving no errors or indication why it is failing.
The gitlab-CI pipeline indicates that it has run fine but no release is created.
The last debug log that can be seen from the gitlab-runner is: 
```bash
 2020-04-10T21:22:30.883Z semantic-release:gitlab file path: 'CHANGELOG.md'
 2020-04-10T21:22:30.884Z semantic-release:gitlab file label: 'official release files'
```

Here is my plugin config:
```yaml
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogTitle: "# CHANGELOG"
  - "@semantic-release/git"
  - - "@semantic-release/gitlab"
    - assets: [{"path": "*.md", "label": "official release files"}]
```

When the assets object is removed from the config the plugin works fine.

Any clues and ideas are much appreciated!

Thank you

**Comment by Dacturne** [comment] 2020-04-24 16:37
Seems the same for me as well.

**Comment by stefan-lacatus** [comment] 2020-04-25 06:02
I'm having the same issue. If I run `semantic-release` locally with the `--no-ci` flag, the publish release with assets works, but it doesn't when it's run in Gitlab CI/CD

**Comment by stefan-lacatus** [comment] 2020-04-25 19:10
Seems to be related to https://github.com/semantic-release/gitlab/issues/139. Our GitLab pipeline was running with `node:latest`. 
After moving to `node:13.8.0` publishing releases works again.

**Comment by isuftin** [comment] 2020-06-26 14:58
I've tested this using NodeJS 14.3.0 in Alpine. Works as expected.

Here's my Dockerfile that creates a working Semantic Release image including the GitLab plugin if you also want to test this on your end:

```
FROM alpine:3.12.0
LABEL maintainer="isuftin@usgs.gov"

RUN apk add --no-cache \
    npm=12.17.0-r0 \
    nodejs-current=14.3.0-r0 \
    git=2.26.2-r0 \
    openssh-client=8.3_p1-r0

# https://github.com/semantic-release/semantic-release/releases
RUN npm install -g semantic-release@17.1.0 \
        # https://github.com/semantic-release/changelog/releases
        @semantic-release/changelog@5.0.1 \
        # https://github.com/semantic-release/exec/releases
        @semantic-release/exec@5.0.0 \
        # https://github.com/semantic-release/git/releases
        @semantic-release/git@9.0.0 \
        # https://github.com/semantic-release/gitlab/releases
        @semantic-release/gitlab@6.0.4 \
        # https://github.com/semantic-release/gitlab-config/releases
        @semantic-release/gitlab-config@8.0.0 \
        # https://github.com/semantic-release/apm/releases
        @semantic-release/apm@3.0.0 \
        # https://github.com/google/semantic-release-replace-plugin/releases
        @google/semantic-release-replace-plugin@1.0.0 \
        # https://github.com/qiwi/semantic-release-gh-pages-plugin/releases
        @qiwi/semantic-release-gh-pages-plugin@3.0.0 \
        # https://github.com/saitho/semantic-release-gitea/releases
        @saithodev/semantic-release-gitea@1.0.0 \
        # https://github.com/conveyal/maven-semantic-release/releases
        # requires a peer of semantic-release@^15.12.3 
        # @conveyal/maven-semantic-release@4.5.0 \
        # https://www.npmjs.com/package/conventional-changelog-conventionalcommits
        conventional-changelog-conventionalcommits@4.3.0 \
        # https://github.com/felixfbecker/semantic-release-docker/releases
        # requires a peer of semantic-release@>=11.0.0 <16.0.0 
        # semantic-release-docker@2.2.0 \ 
        # https://github.com/carlos-cubas/semantic-release-gcr/releases
        # requires a peer of semantic-release@>=11.0.0 <16.0.0 
        # semantic-release-gcr@1.0.26 \
        # https://github.com/raix/semantic-release-vsce/releases
        semantic-release-vsce@3.0.1 \
        # https://github.com/piercus/semantic-release-verify-deps/releases
        semantic-release-verify-deps@1.0.2 \
        # https://github.com/GabrielDuarteM/semantic-release-chrome/releases
        semantic-release-chrome@1.1.3 \
        # https://github.com/pascalMN/semantic-release-gerrit/releases
        # requires a peer of semantic-release@^15.8.0 
        # semantic-release-gerrit@1.1.4 \
        # https://github.com/byCedric/semantic-release-expo/releases
        semantic-release-expo@2.2.3 \
        # https://github.com/lluchmk/semantic-release-ado/releases
        # requires a peer of semantic-release@>=11.0.0 <16.0.0 
        #semantic-release-ado@1.2.1 \
        # https://github.com/KengoTODA/gradle-semantic-release-plugin/releases
        gradle-semantic-release-plugin@1.4.1 \
        # https://github.com/juliuscc/semantic-release-slack-bot/releases
        semantic-release-slack-bot@1.6.2 \
        # https://www.npmjs.com/package/conventional-changelog-atom
        conventional-changelog-atom@2.0.7 \
        # https://www.npmjs.com/package/conventional-changelog-angular
        conventional-changelog-angular@5.0.10 \
        # https://www.npmjs.com/package/conventional-changelog-codemirror
        conventional-changelog-codemirror@2.0.7 \
        # https://www.npmjs.com/package/conventional-changelog-ember
        conventional-changelog-ember@2.0.8 \
        # https://www.npmjs.com/package/conventional-changelog-eslint
        conventional-changelog-eslint@3.0.8 \
        # https://www.npmjs.com/package/conventional-changelog-express
        conventional-changelog-express@2.0.5 \
        # https://www.npmjs.com/package/conventional-changelog-jquery
        conventional-changelog-jquery@3.0.6 \
        # https://github.com/NoxHarmonium/leiningen-semantic-release/releases
        # requires a peer of semantic-release@^15.13.24 
        # leiningen-semantic-release@1.0.4 \
        # https://www.npmjs.com/package/conventional-changelog-jshint
        conventional-changelog-jshint@2.0.7 && \
        npm cache verify

RUN mkdir -p ~/.ssh && chmod 700 ~/.ssh
```

**Comment by fgreinacher** [comment] 2022-04-11 07:40
Closing this as it seems to be a duplicate of #139.

Feel free to reopen if I got this wrong!

**Closed by fgreinacher** 2022-04-11 07:40 UTC
